const QUESTIONS = {
    "de":[
        "Vorlesung lieber Online oder im Hörsaal?",
        "Lieber ein Spieleabend mit Freunden Zuhause oder zusammen Zocken?",
        "Lieber über eine Dating App das perfekte Match finden oder im real live einen Partner suchen?",
        "Schaust du gerne Fotoalben an oder erfreust du dich an Instagramfeeds?",
        "Lässt du dich von einem Handy wecken oder von einem Wecker?",
        "Gehst du lieber in einem Restaurant essen oder bestellst du dein Essen?",
        "Kino oder Netflix?",
        "Wann hast du als letztes ein Foto gemacht und mit was?",
        "Was war dein schönstes Urlaubserlebnis? ",
        "Gehst du zu einem Reisebüro oder buchst du online?",
        "Welches ist dein Lieblingslied und was bedeutet es dir und welches Medium nutzt du? ",
        "Welcher deiner Freunde hat dich am meisten geprägt? ",
        "Hast du einen Lieblingsplatz, an den du mich mitnehmen würdest? ",
        "Glaubst du, dass es wichtig ist etwas Künstlerisches zu lernen? ",
        "Was war das lustigste, das du jemals in der Schule erlebt hast? ",
        "Hast du vor kurzem ein interessantes Buch gelesen (Print oder Digital)? ",
        "Was machst du, wenn dir manchmal langweilig ist? ",
        "Hast du Haustiere oder hattest mal welche? Welches Haustier hättest du am liebsten? (Kennst du noch Pou oder Tamagotchi?)",
        "Warst du schon mal in der Tanzschule? Kannst du tanzen? ",
        "Was bringt dich immer zum Lachen? ",
        "Hast im letzten Jahr ein Online Konzert oder Festival besucht? ",
        "Was hast du zuletzt gekocht? ",
        "Wie oft nutzt du Chefkoch oder ein Kochbuch?",
        "Was war deine kreativste Verkleidung zu Halloween oder Karneval? ",
        "Was hat dich zuletzt emotional sehr berührt? ",
        "Gehst du lieber Campen oder ins Hotel? ",
        "Was war der beste Ratschlag, den du je bekommen hast? ",
        "Welches ist dein Lieblingsbuch/ -film und/oder wer ist dein Lieblingsautor/ -schauspieler? ",
        "Wenn du drei Personen aus der Geschichte zum Essen einladen könntest, welche wären das? ",
        "Welches Land würdest du am liebsten bereisen und warum? ",
        "Was würdest du in der Welt gerne verändern? ",
        "Wenn heute die Welt untergeht, wie würdest du deine restliche Zeit gerne verbringen? ",
        "Was hat dich motiviert hier in Freiberg ein Studium zu beginnen ? ",
        "Mit welchen drei Worten würdest du dich beschreiben? ",
        "Hast du schon einmal ein Geschenk weiterverschenkt? ",
        "Wofür bist du am dankbarsten? ",
        "Kommst du normalerweise zu früh oder zu spät? ",
        "Welche fremde Stadt hat dich zuletzt begeistert und warum? ",
        "Welche drei Dinge machen dich richtig wütend?"
      ],
   "en":[
        "Would you rather attend a lecture online or in the lecture hall?",
        "Do you prefer a game night with friends at home or gaming together?",
        "Would you rather find the perfect match on a dating app or search for a partner in real live?",
        "Do you like looking at photo albums or enjoying Instagram feeds?",
        "Do you let a cell phone wake you up or an alarm clock?",
        "Do you prefer going out to eat at a restaurant or ordering your food?",
        "Go to the movies or watch Netflix?",
        "When was the last time you took a photo and with what?",
        "What was your best vacation experience? ",
        "Do you go to a travel agent or book online?",
        "What is your favorite song and what does it mean to you and what medium do you use? ",
        "Which of your friends has had the most impact on you? ",
        "Do you have a favorite place you would take me? ",
        "Do you think it's important to learn something artistic? ",
        "What was the funniest thing you ever experienced at school? ",
        "Have you read an interesting book recently (print or digital)? ",
        "What do you do when you're bored sometimes? ",
        "Do you have pets or used to have pets? Which pet would you most like to have? (Do you remember Pou or Tamagotchi?)",
        "Have you ever been to dance school? Can you dance? ",
        "What always makes you laugh? ",
        "Have you attended an online concert or festival in the last year? ",
        "What was the last thing you cooked? ",
        "How often do you use Chef or a cookbook?",
        "What was your most creative costume for Halloween or Mardi Gras? ",
        "What touched you emotionally most recently? ",
        "Do you prefer to go camping or stay in a hotel? ",
        "What was the best piece of advice you ever got? ",
        "What is your favorite book/movie and/or who is your favorite author/actor? ",
        "If you could invite three people from history to dinner, who would they be? ",
        "What country would you most like to travel to and why? ",
        "What would you like to change in the world? ",
        "If the world ended today, how would you like to spend the rest of your time? ",
        "What motivated you to start studying here in Freiberg? ",
        "What three words would you use to describe yourself? ",
        "Have you ever given a gift to someone else? ",
        "What are you most grateful for? ",
        "Do you usually arrive too early or too late? ",
        "Which foreign city has excited you most recently and why? ",
        "What three things make you really angry?"
       ]
 };
