const QUESTIONS = [
  "Vorlesung lieber Online oder im Hörsaal?",
  "Lieber ein Spieleabend mit Freunden Zuhause oder zusammen Zocken?",
  "Lieber über eine Dating App das perfekte Match finden oder im real live einen Partner suchen?",
  "Schaust du gerne Fotoalben an oder erfreust du dich an Instagramfeeds?",
  "Lässt du dich von einem Handy wecken oder von einem Wecker?",
  "Gehst du lieber in einem Restaurant essen oder bestellst du dein Essen?",
  "Kino oder Netflix?",
  "Wann hast du als letztes ein Foto gemacht und mit was?",
  "Was war dein schönstes Urlaubserlebnis? ",
  "Gehst du zu einem Reisebüro oder buchst du online?",
  "Welches ist dein Lieblingslied und was bedeutet es dir und welches Medium nutzt du? ",
  "Welcher deiner Freunde hat dich am meisten geprägt? ",
  "Hast du einen Lieblingsplatz, an den du mich mitnehmen würdest? ",
  "Glaubst du, dass es wichtig ist etwas Künstlerisches zu lernen? ",
  "Was war das lustigste, das du jemals in der Schule erlebt hast? ",
  "Hast du vor kurzem ein interessantes Buch gelesen (Print oder Digital)? ",
  "Was machst du, wenn dir manchmal langweilig ist? ",
  "Hast du Haustiere oder hattest mal welche? Welches Haustier hättest du am liebsten? (Kennst du noch Pou oder Tamagotchi?)",
  "Warst du schon mal in der Tanzschule? Kannst du tanzen? ",
  "Was bringt dich immer zum Lachen? ",
  "Hast im letzten Jahr ein Online Konzert oder Festival besucht? ",
  "Was hast du zuletzt gekocht? ",
  "Wie oft nutzt du Chefkoch oder ein Kochbuch?",
  "Was war deine kreativste Verkleidung zu Halloween oder Karneval? ",
  "Was hat dich zuletzt emotional sehr berührt? ",
  "Gehst du lieber Campen oder ins Hotel? ",
  "Was war der beste Ratschlag, den du je bekommen hast? ",
  "Welches ist dein Lieblingsbuch/ -film und/oder wer ist dein Lieblingsautor/ -schauspieler? ",
  "Wenn du drei Personen aus der Geschichte zum Essen einladen könntest, welche wären das? ",
  "Welches Land würdest du am liebsten bereisen und warum? ",
  "Was würdest du in der Welt gerne verändern? ",
  "Wenn heute die Welt untergeht, wie würdest du deine restliche Zeit gerne verbringen? ",
  "Was hat dich motiviert hier in Freiberg ein Studium zu beginnen ? ",
  "Mit welchen drei Worten würdest du dich beschreiben? ",
  "Hast du schon einmal ein Geschenk weiterverschenkt? ",
  "Wofür bist du am dankbarsten? ",
  "Kommst du normalerweise zu früh oder zu spät? ",
  "Welche fremde Stadt hat dich zuletzt begeistert und warum? ",
  "Welche drei Dinge machen dich richtig wütend?"

];
